point付与/取得APIのvalidation追加
cloudnativedaysjp/dreamkast-functions pull request #44
Opened 2022-11-07 03:44 UTC by ystkfujii

2022-11-09 14:33 UTC, ystkfujii commented on src/get_profile_point.ts
> +                const cp = ppr['conference#timestamp']
同一のQRコードを使いまわす(=pointEventIdを使いまわす)となったので、conferenceとpointEventIdの組み合わせによる重複をチェックを削除しました。

2022-11-09 15:25 UTC, hrk091 requested changes
いくつかコメントしたので、確認・ご対応のほどお願いします！

2022-11-09 15:25 UTC, hrk091 commented on lib/profile-point-stack.ts
> +        // Dynam DB: pointEventReason
```suggestion
        // Dynamo DB: pointEventTable
```

2022-11-09 15:25 UTC, hrk091 commented on lib/schemas/index.ts
> +    title: 'profilePointRequestResponse',
titleが `xxxRequestResponse` となっていますが、Request payloadのschemaを指していると思うので違和感があります。このようにされた理由は何でしょうか？（他のJsonSchemaも同様です）

2022-11-09 15:25 UTC, hrk091 commented on src/get_profile_point.ts
> +                const cp = ppr['conference#timestamp']
説明が言葉足らずですみません。
「同一のQRコードを使い回す」= 「pointEventIdを使い回す」ではなく、同一のQRコードを使うけど、dk側でtime slotに応じて異なるpointEventIdにマッピングし、そのpointEventIdを使ってlambdaにリクエストする、という構成になります。

このため、「conferenceとpointEventIdの組み合わせによる重複チェック」は必要です

2022-11-09 16:23 UTC, ystkfujii commented
> いくつかコメントしたので、確認・ご対応のほどお願いします！

対応しました！ 

dynamoDBに下記のようなイベント登録しています

![image](https://user-images.githubusercontent.com/76274657/200884186-cf2e223c-e2d3-4abc-adc1-2113d8597261.png)

なので以下のように使用できます

```bash
curl -H "Content-Type: application/json" -XPOST -d "{ \"pointEventId\": \"hoge1\",\"conference\": \"cn1\" }" https://api.dev.cloudnativedays.jp/api/v1/profile/123/point
curl -H "Content-Type: application/json" -XPOST -d "{ \"pointEventId\": \"hoge3\",\"conference\": \"cn1\" }" https://api.dev.cloudnativedays.jp/api/v1/profile/123/point
curl  https://api.dev.cloudnativedays.jp/api/v1/profile/123/points?conference=cn1
```

2022-11-10 00:52 UTC, hrk091 approved these changes
ご対応ありがとうございます！
LGTMです

2022-11-10 00:52 UTC, merged