Feat/change event abbr to cicd2023
cloudnativedaysjp/dreamkast-functions pull request #70
Opened 2023-02-12 04:35 UTC by ystkfujii

2023-02-12 06:35 UTC, ystkfujii commented
どなたかレビューお願いします

2023-02-12 09:19 UTC, jacopen requested changes

2023-02-12 09:19 UTC, jacopen commented on lib/viewerCountLambda.ts
> +  console.log('hogehoge')
これはいらないです！

2023-02-12 09:25 UTC, ystkfujii commented on lib/viewerCountLambda.ts
> +  console.log('hogehoge')
🙇

2023-02-18 04:42 UTC, hrk091 approved these changes
ありがとうございます！LGTMです

2023-02-23 02:06 UTC, merged